# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0003_auto_20161012_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentdrip',
            name='opened',
        ),
        migrations.AddField(
            model_name='sentdrip',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
